seed: 42
# [64, 64][128, 128][256, 128]X
# [128, 128, 64] [32, 32, 32][64, 64, 64][128, 128, 128]X
# [128, 128, 64, 32][256, 128, 64, 32][256, 256, 128, 64][64, 64, 64, 64][64, 64, 32, 16]X
# Models are instantiated using skrl's model instantiator utility
# https://skrl.readthedocs.io/en/latest/api/utils/model_instantiators.html
models:
  separate: True
  policy:  # see gaussian_model parameters
    class: GaussianMixin
    clip_actions: False
    clip_log_std: True
    # min_log_std: -0.5      # ≈ std 0.61
    # min_log_std: -20.0
    # max_log_std: 2.0
    # max_log_std:  0.18  # std = 1.2
    # initial_log_std: 0.0
    # min_log_std: -2.0           # 约等于 std ≈ 0.135
    min_log_std: -1.2          # 约等于 std ≈ 0.3
    # max_log_std:  0.0           # 上限改到 log_std=0 → std=1.0
    max_log_std:  0.18  # std = 1.2
    initial_log_std: 0.0      # 初始 std ≈ 0.74（不会一上来就顶上限）
    network:
      - name: net
        input: STATES
        layers: [512, 256, 128, 64]
        activations: elu
    output: ACTIONS
  value:  # see deterministic_model parameters
    class: DeterministicMixin
    clip_actions: False
    network:
      - name: net
        input: STATES
        layers: [512, 256, 128, 64]
        activations: elu
    output: ONE


# Rollout memory
# https://skrl.readthedocs.io/en/latest/api/memories/random.html
memory:
  class: RandomMemory
  memory_size: -1  # automatically determined (same as agent:rollouts)


# MAPPO agent configuration (field names are from MAPPO_DEFAULT_CONFIG)
# https://skrl.readthedocs.io/en/latest/api/multi_agents/mappo.html
agent:
  class: MAPPO
  param_sharing: True
  rollouts: 250
  learning_epochs: 5
  mini_batches: 100
  discount_factor: 0.99
  lambda: 0.95
  learning_rate: 0.00005
  # learning_rate_scheduler: null
  learning_rate_scheduler: KLAdaptiveLR
  learning_rate_scheduler_kwargs:
    kl_threshold: 0.01
    max_lr: 0.0001
  state_preprocessor: RunningStandardScaler           # 归一化obs
  state_preprocessor_kwargs: null
  shared_state_preprocessor: RunningStandardScaler    # 归一化state
  shared_state_preprocessor_kwargs: null
  value_preprocessor: RunningStandardScaler
  value_preprocessor_kwargs: null
  random_timesteps: 0
  learning_starts: 0
  grad_norm_clip: 1.0
  ratio_clip: 0.2
  value_clip: 0.2
  clip_predicted_values: True
  entropy_loss_scale: 0.005
  value_loss_scale: 1.0
  # kl_threshold: 0.01
  rewards_shaper_scale: 1.0
  time_limit_bootstrap: False
  # logging and checkpoint
  experiment:
    directory: ""
    experiment_name: ""
    write_interval: auto
    checkpoint_interval: 10000


# Sequential trainer
# https://skrl.readthedocs.io/en/latest/api/trainers/sequential.html
trainer:
  class: SequentialTrainer
  timesteps: 10000000
  environment_info: log
