seed: 42
# Models are instantiated using skrl's model instantiator utility
# https://skrl.readthedocs.io/en/latest/api/utils/model_instantiators.html
models:
  separate: True
  policy:  # see gaussian_model parameters
    class: GaussianMixin
    clip_actions: False
    clip_log_std: True
    # min_log_std: -0.22  # std = 0.8
    # min_log_std: -0.36  # std = 0.7
    # min_log_std: -0.51  # std = 0.6
    # min_log_std: -0.7  # std = 0.5
    # min_log_std: -0.9  # std = 0.4
    min_log_std: -1.2  # std = 0.3
    # min_log_std: -1.6  # std = 0.2
    # min_log_std: -2.3  # std = 0.1
    # min_log_std: -3.0  # std = 0.05
    # min_log_std: -4.6  # std = 0.01
    # min_log_std: -7.0  # std = 0.001
    # min_log_std: -0.5      # ≈ std 0.61
    # max_log_std: 0.7  # std = 2.0
    max_log_std:  0.18  # std = 1.2
    initial_log_std: 0.0
    network:
      - name: net
        input: STATES
        # layers: [512, 512, 256, 256, 128, 128]
        layers: [512, 256, 128, 64]
        # layers: [1024, 512, 256, 128]
        activations: elu
    output: ACTIONS
  value:  # see deterministic_model parameters
    class: DeterministicMixin
    clip_actions: False
    network:
      - name: net
        input: STATES
        layers: [512, 256, 128, 64]
        activations: elu
    output: ONE


# Rollout memory
# https://skrl.readthedocs.io/en/latest/api/memories/random.html
memory:
  class: RandomMemory
  memory_size: -1  # automatically determined (same as agent:rollouts)


# IPPO agent configuration (field names are from IPPO_DEFAULT_CONFIG)
# https://skrl.readthedocs.io/en/latest/api/multi_agents/ippo.html
agent:
  class: IPPO
  param_sharing: True
  rollouts: 250                   # 每一次policy更新前，每个环境要往前滚多少步，也就是每轮收集的“轨迹长度” 。采样多少步之后更新一次网络
  # rollouts: 100
  learning_epochs: 5              # 每采集完一批rollouts数据后，要在这批“固定数据”上反复训练多少轮。一次采样到的这批数据，被拿来训练几轮。影响的是：每条样本被重复利用多少次。

  # Stage 1: 1000 ~ 2000 envs, 4 mini-batches
  # mini_batches: 4

  # Stage 2, 3
  # mini_batches: 65  # RTX 4090: 13000 envs, 65 mini-batches
  # mini_batches: 35  # RTX 4070 Ti SUPER: 7000 envs, 35 mini-batches
  mini_batches: 100               # 把当前这批rollout数据按多少个小批次来做SGD更新。采样得到的大 batch，拆成多少个小批次做梯度下降。影响的是：每个 mini-batch 的大小和梯度噪声大小。

  discount_factor: 0.99
  lambda: 0.95
  learning_rate: 0.00005
  learning_rate_scheduler: KLAdaptiveLR
  # learning_rate_scheduler: null
  learning_rate_scheduler_kwargs:
    kl_threshold: 0.01
    max_lr: 0.0001
  state_preprocessor: RunningStandardScaler
  state_preprocessor_kwargs: null
  value_preprocessor: RunningStandardScaler     # 将 Critic 网络预测的价值（Value）和真实回报（Return/Target）归一化
  # value_preprocessor: null
  value_preprocessor_kwargs: null
  random_timesteps: 0
  learning_starts: 0
  grad_norm_clip: 1.0
  ratio_clip: 0.2
  value_clip: 0.2
  clip_predicted_values: True           # 限制critic每一步更新幅度。限制了Critic网络在一次更新（Update）中，对同一状态的价值预测发生剧烈改变
  entropy_loss_scale: 0.001
  value_loss_scale: 1.0
  # kl_threshold: 0.02
  rewards_shaper_scale: 1.0
  time_limit_bootstrap: False
  # logging and checkpoint
  experiment:
    directory: ""
    experiment_name: ""
    write_interval: auto
    checkpoint_interval: 10000


# Sequential trainer
# https://skrl.readthedocs.io/en/latest/api/trainers/sequential.html
trainer:
  class: SequentialTrainer
  timesteps: 10000000
  environment_info: log
