# Reference: https://github.com/DLR-RM/rl-baselines3-zoo/blob/master/hyperparams/ppo.yml
seed: 42

policy: 'MlpPolicy'
policy_kwargs: "dict(
                    log_std_init=-2.302585093,
                    ortho_init=False,
                    activation_fn=nn.ReLU,
                    net_arch=dict(pi=[256, 256, 128], vf=[256, 256, 128]),
                )"
device: "cpu"
n_timesteps: !!float 1e8
batch_size: 150000  # batch_size = (n_envs * n_steps) / 4  <-- from Lao Yuan ^-^
n_steps: 30
gamma: 0.99
learning_rate: !!float 1e-4
# ent_coef: 0.0
ent_coef: 0.005
clip_range: 0.2
n_epochs: 4
gae_lambda: 0.95
max_grad_norm: 1.0
vf_coef: 0.5
