# Reference: https://github.com/DLR-RM/rl-baselines3-zoo/blob/master/hyperparams/ppo.yml
seed: 42

policy: 'MlpPolicy'
policy_kwargs: "dict(
                    log_std_init=0.0,
                    ortho_init=False,
                    activation_fn=nn.ReLU,
                    net_arch=dict(pi=[1024, 512], vf=[1024, 512]),
                )"
device: "cpu"
n_timesteps: !!float 1e8  # Gaurav Sukhatme does 1e9 (1B) steps #^# (https://www.youtube.com/watch?v=M9oH0fn9uq0
batch_size: 125000  # batch_size = (n_envs * n_steps) / 4 <-- from Lao Yuan ^-^
# n_steps: 100  # 10 steps/sec for waypoint envs
n_steps: 500  # 50 steps/sec for bodyrate envs
gamma: 0.99
learning_rate: !!float 1e-4
# ent_coef: 0.0
ent_coef: 0.0005
clip_range: 0.2
n_epochs: 4
gae_lambda: 0.95
max_grad_norm: 1.0
vf_coef: 0.5
