seed: 42


# Models are instantiated using skrl's model instantiator utility
# https://skrl.readthedocs.io/en/latest/api/utils/model_instantiators.html
models:
  separate: False
  policy:  # see gaussian_model parameters
    class: GaussianMixin
    clip_actions: False
    clip_log_std: True
    min_log_std: -0.22  # std = 0.8
    # min_log_std: -0.36  # std = 0.7
    # min_log_std: -0.51  # std = 0.6
    # min_log_std: -0.7  # std = 0.5
    # min_log_std: -0.9  # std = 0.4
    # min_log_std: -1.2  # std = 0.3
    # min_log_std: -1.6  # std = 0.2
    # min_log_std: -2.3  # std = 0.1
    # min_log_std: -3.0  # std = 0.05
    # min_log_std: -4.6  # std = 0.01
    # min_log_std: -7.0  # std = 0.001
    max_log_std: 0.7  # std = 2.0
    initial_log_std: 0.0
    network:
      - name: net
        input: STATES
        layers: [1024, 1024, 1024, 512, 512, 512, 256, 256, 256]
        activations: elu
    output: ACTIONS
  value:  # see deterministic_model parameters
    class: DeterministicMixin
    clip_actions: False
    network:
      - name: net
        input: STATES
        layers: [1024, 1024, 1024, 512, 512, 512, 256, 256, 256]
        activations: elu
    output: ONE


# Rollout memory
# https://skrl.readthedocs.io/en/latest/api/memories/random.html
memory:
  class: RandomMemory
  memory_size: -1  # automatically determined (same as agent:rollouts)


# IPPO agent configuration (field names are from IPPO_DEFAULT_CONFIG)
# https://skrl.readthedocs.io/en/latest/api/multi_agents/ippo.html
agent:
  class: IPPO
  shared_parameters: True
  # rollouts: 100  # 10 steps/sec for waypoint envs
  # rollouts: 150  # 50 steps/sec for bodyrate envs
  rollouts: 100  # 10 steps/sec for ideal velocity envs
  learning_epochs: 5
  mini_batches: 20
  discount_factor: 0.99
  lambda: 0.95
  learning_rate: 1.0e-04
  learning_rate_scheduler: KLAdaptiveLR
  # learning_rate_scheduler: null
  learning_rate_scheduler_kwargs:
    kl_threshold: 0.016
    max_lr: 0.0005
  state_preprocessor: RunningStandardScaler
  state_preprocessor_kwargs: null
  value_preprocessor: RunningStandardScaler
  value_preprocessor_kwargs: null
  random_timesteps: 0
  learning_starts: 0
  grad_norm_clip: 1.0
  ratio_clip: 0.2
  value_clip: 0.2
  clip_predicted_values: True
  entropy_loss_scale: 0.005
  value_loss_scale: 1.0
  kl_threshold: 0.0
  rewards_shaper_scale: 1.0
  time_limit_bootstrap: True
  # logging and checkpoint
  experiment:
    directory: ""
    experiment_name: ""
    write_interval: auto
    checkpoint_interval: 2000


# Sequential trainer
# https://skrl.readthedocs.io/en/latest/api/trainers/sequential.html
trainer:
  class: SequentialTrainer
  timesteps: 500000
  environment_info: log
